name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        if: success()
        uses: actions/checkout@v1
        with:
          ref: main
      - name: checkout-main
        if: success()
        run: git checkout main
      - name: checkout
        if: success()
        uses: actions/checkout@v1
      # There is no need to do this if you are not installing from source
      - name: setup
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.7
      - name: make local
        if: success()
        run: make local
